stages:
  parse_nrel118_bus_data:
    desc: "Parse bus data from the NREL-118 dataset"
    cmd: python src/data/parse_nrel118_buses.py
      data/raw/nrel118/additional-files-mti-118/Buses.csv
      data/parsed/nrel118_buses.csv
    deps:
      - data/raw/nrel118/additional-files-mti-118/Buses.csv
      - src/data/parse_nrel118_buses.py
    outs:
      - data/parsed/nrel118_buses.csv

  parse_nrel118_line_data:
    desc: "Parse line data from the NREL-118 dataset"
    cmd: python src/data/parse_nrel118_lines.py
      data/raw/nrel118/additional-files-mti-118/Lines.csv
      data/parsed/nrel118_lines.csv
    deps:
      - data/raw/nrel118/additional-files-mti-118/Lines.csv
      - src/data/parse_nrel118_lines.py
    outs:
      - data/parsed/nrel118_lines.csv

  parse_jeas118_line_data:
    desc: "Parse line data from the JEAS-118 dataset"
    cmd: python src/data/parse_jeas118_lines.py
      data/raw/jeas118/JEAS_IEEE118.doc
      data/parsed/jeas118_lines.csv
    deps:
      - data/raw/jeas118/JEAS_IEEE118.doc
      - src/data/parse_jeas118_lines.py
    outs:
      - data/parsed/jeas118_lines.csv

  parse_jeas118_trafo_data:
    desc: "Parse transformer data from the JEAS-118 dataset"
    cmd: python src/data/parse_jeas118_trafos.py
      data/raw/jeas118/JEAS_IEEE118.doc
      data/parsed/jeas118_trafos.csv
    deps:
      - src/data/parse_jeas118_trafos.py
      - data/raw/jeas118/JEAS_IEEE118.doc
    outs:
      - data/parsed/jeas118_trafos.csv

  parse_jeas118_load_data:
    desc: "Parse load data from the JEAS-118 dataset"
    cmd: python src/data/parse_jeas118_loads.py
      data/raw/jeas118/JEAS_IEEE118.doc
      data/parsed/jeas118_loads.csv
    deps:
      - src/data/parse_jeas118_loads.py
      - data/raw/jeas118/JEAS_IEEE118.doc
    outs:
      - data/parsed/jeas118_loads.csv

  parse_nrel118_load_ts_data:
    desc: "Parse time-series load data from the NREL-118 dataset"
    cmd: python src/data/parse_nrel118_load_ts.py
      "data/raw/nrel118/Input files/RT/Load"
      data/parsed/nrel118_loads_ts.csv
    deps:
      - src/data/parse_nrel118_load_ts.py
      - data/raw/nrel118/Input files/RT/Load
    outs:
      - data/parsed/nrel118_loads_ts.csv

  parse_nrel118_gen_data:
    desc: "Parse generation data from the NREL-118 dataset"
    cmd: python src/data/parse_nrel118_gens.py
      data/raw/nrel118/additional-files-mti-118/Generators.csv
      data/parsed/nrel118_gens.csv
    deps:
      - src/data/parse_nrel118_gens.py
      - data/raw/nrel118/additional-files-mti-118/Generators.csv
    outs:
      - data/parsed/nrel118_gens.csv

  parse_nrel118_escalator_ts_data:
    desc: "Parse escalator time-series data from the NREL-118 dataset"
    cmd: python src/data/parse_nrel118_escalator_ts.py
      data/raw/nrel118/additional-files-mti-118/Escalators.csv
      data/parsed/nrel118_escalator_ts.csv
    deps:
      - src/data/parse_nrel118_escalator_ts.py
      - data/raw/nrel118/additional-files-mti-118/Escalators.csv
    outs:
      - data/parsed/nrel118_escalator_ts.csv

  parse_nrel118_hydro_nondisp_ts_data:
    desc: "Parse hydro plants time-series data from the NREL-118 dataset"
    cmd: python src/data/parse_nrel118_hydro_nondisp_ts.py
      data/raw/nrel118/additional-files-mti-118/Hydro_nondipatchable.csv
      data/parsed/nrel118_hydro_nondisp_ts.csv
    deps:
      - src/data/parse_nrel118_hydro_nondisp_ts.py
      - data/raw/nrel118/additional-files-mti-118/Hydro_nondipatchable.csv
    outs:
      - data/parsed/nrel118_hydro_nondisp_ts.csv

  parse_nrel118_hydro_ts_data:
    desc: "Parse time-series hydro plants data from the NREL-118 dataset"
    cmd: python src/data/parse_nrel118_hydro_ts.py
      "data/raw/nrel118/Input files/Hydro"
      data/parsed/nrel118_hydro_ts.csv
    deps:
      - src/data/parse_nrel118_hydro_ts.py
      - data/raw/nrel118/Input files/Hydro
    outs:
      - data/parsed/nrel118_hydro_ts.csv

  parse_nrel118_solar_ts_data:
    desc: "Parse time-series solar plants data from the NREL-118 dataset"
    cmd: python src/data/parse_nrel118_solar_ts.py
      "data/raw/nrel118/Input files/RT/Solar"
      data/parsed/nrel118_solar_ts.csv
    deps:
      - src/data/parse_nrel118_solar_ts.py
      - data/raw/nrel118/Input files/RT/Solar
    outs:
      - data/parsed/nrel118_solar_ts.csv

  parse_nrel118_wind_ts_data:
    desc: "Parse time-series wind plants data from the NREL-118 dataset"
    cmd: python src/data/parse_nrel118_wind_ts.py
      "data/raw/nrel118/Input files/RT/Wind"
      data/parsed/nrel118_wind_ts.csv
    deps:
      - src/data/parse_nrel118_wind_ts.py
      - data/raw/nrel118/Input files/RT/Wind
    outs:
      - data/parsed/nrel118_wind_ts.csv

  parse_nrel118_outage_ts_data:
    desc: "Parse time-series outage data from the NREL-118 dataset"
    cmd: python src/data/parse_nrel118_outage_ts.py
      "data/raw/nrel118/Input files/Others/GenOut.csv"
      data/parsed/nrel118_outage_ts.csv
    deps:
      - src/data/parse_nrel118_outage_ts.py
      - data/raw/nrel118/Input files/Others/GenOut.csv
    outs:
      - data/parsed/nrel118_outage_ts.csv

  transform_load_data:
    desc: "Combine necessary load variables for preparation stages"
    cmd: python src/data/transform_loads.py
      data/parsed/nrel118_buses.csv
      data/parsed/jeas118_loads.csv
      data/transformed/loads.csv
    deps:
      - data/parsed/nrel118_buses.csv
      - data/parsed/jeas118_loads.csv
      - src/data/transform_loads.py
    outs:
      - data/transformed/loads.csv

  prepare_bus_data:
    desc: "Build final bus dataset"
    cmd: python src/data/prepare_buses.py
      data/parsed/nrel118_buses.csv
      data/prepared/buses.csv
    deps:
      - data/parsed/nrel118_buses.csv
      - src/data/prepare_buses.py
    outs:
      - data/prepared/buses.csv

  prepare_branch_data:
    desc: "Build final dataset with line and transformer info"
    cmd: python src/data/prepare_branches.py
      data/parsed/nrel118_lines.csv
      data/parsed/jeas118_lines.csv
      data/parsed/jeas118_trafos.csv
      data/prepared/buses.csv
      data/prepared/branches.csv
    deps:
      - src/data/prepare_branches.py
      - data/parsed/nrel118_lines.csv
      - data/parsed/jeas118_lines.csv
      - data/parsed/jeas118_trafos.csv
      - data/prepared/buses.csv
    outs:
      - data/prepared/branches.csv

  prepare_load_data:
    desc: "Build final dataset with load info"
    cmd: python src/data/prepare_loads.py
      data/transformed/loads.csv
      data/parsed/nrel118_loads_ts.csv
      data/prepared/loads.csv
    deps:
      - src/data/prepare_loads.py
      - data/transformed/loads.csv
      - data/parsed/nrel118_loads_ts.csv
    outs:
      - data/prepared/loads.csv

  prepare_load_ts_data:
    desc: "Build final dataset with load time-series data"
    cmd: python src/data/prepare_loads_ts.py
      data/transformed/loads.csv
      data/parsed/nrel118_loads_ts.csv
      data/prepared/loads_ts.csv
    deps:
      - src/data/prepare_loads_ts.py
      - data/transformed/loads.csv
      - data/parsed/nrel118_loads_ts.csv
    outs:
      - data/prepared/loads_ts.csv
