stages:
  parse_nrel118_buses:
    desc: "Parse bus data from the NREL-118 dataset"
    cmd: python src/data/parse_nrel118_buses.py
      data/raw/nrel118/additional-files-mti-118/Buses.csv
      data/parsed/nrel118_buses.csv
    deps:
      - data/raw/nrel118/additional-files-mti-118/Buses.csv
      - src/data/parse_nrel118_buses.py
      - src/utils/data_loaders/load_df_data.py
    outs:
      - data/parsed/nrel118_buses.csv

  parse_nrel118_lines:
    desc: "Parse line data from the NREL-118 dataset"
    cmd: python src/data/parse_nrel118_lines.py
      data/raw/nrel118/additional-files-mti-118/Lines.csv
      data/parsed/nrel118_lines.csv
    deps:
      - data/raw/nrel118/additional-files-mti-118/Lines.csv
      - src/data/parse_nrel118_lines.py
      - src/utils/data_loaders/load_df_data.py
    outs:
      - data/parsed/nrel118_lines.csv

  parse_jeas118_lines:
    desc: "Parse line data from the JEAS-118 dataset"
    cmd: python src/data/parse_jeas118_lines.py
      data/raw/jeas118/JEAS_IEEE118.doc
      data/parsed/jeas118_lines.csv
    deps:
      - data/raw/jeas118/JEAS_IEEE118.doc
      - src/data/parse_jeas118_lines.py
      - src/utils/converters.py
    outs:
      - data/parsed/jeas118_lines.csv

  parse_jeas118_trafos:
    desc: "Parse transformer data from the JEAS-118 dataset"
    cmd: python src/data/parse_jeas118_trafos.py
      data/raw/jeas118/JEAS_IEEE118.doc
      data/parsed/jeas118_trafos.csv
    deps:
      - src/data/parse_jeas118_trafos.py
      - data/raw/jeas118/JEAS_IEEE118.doc
      - src/utils/converters.py
    outs:
      - data/parsed/jeas118_trafos.csv

  parse_jeas118_loads:
    desc: "Parse load data from the JEAS-118 dataset"
    cmd: python src/data/parse_jeas118_loads.py
      data/raw/jeas118/JEAS_IEEE118.doc
      data/parsed/jeas118_loads.csv
    deps:
      - src/data/parse_jeas118_loads.py
      - data/raw/jeas118/JEAS_IEEE118.doc
      - src/utils/converters.py
    outs:
      - data/parsed/jeas118_loads.csv

  parse_nrel118_loads_ts:
    desc: "Parse time-series load data from the NREL-118 dataset"
    cmd: python src/data/parse_nrel118_loads_ts.py
      "data/raw/nrel118/Input files/RT/Load"
      data/parsed/nrel118_loads_ts.csv
    deps:
      - src/data/parse_nrel118_loads_ts.py
      - data/raw/nrel118/Input files/RT/Load
      - src/utils/data_loaders/load_ts_data.py
    outs:
      - data/parsed/nrel118_loads_ts.csv

  parse_nrel118_gens:
    desc: "Parse generation data from the NREL-118 dataset"
    cmd: python src/data/parse_nrel118_gens.py
      data/raw/nrel118/additional-files-mti-118/Generators.csv
      data/parsed/nrel118_gens.csv
    deps:
      - src/data/parse_nrel118_gens.py
      - data/raw/nrel118/additional-files-mti-118/Generators.csv
      - src/utils/data_loaders/load_df_data.py
    params:
      - definitions.py:
          - GEN_TYPES
          - DATE_FORMAT
    outs:
      - data/parsed/nrel118_gens.csv

  parse_nrel118_escalators_ts:
    desc: "Parse escalator time-series data from the NREL-118 dataset"
    cmd: python src/data/parse_nrel118_escalators_ts.py
      data/raw/nrel118/additional-files-mti-118/Escalators.csv
      data/parsed/nrel118_escalators_ts.csv
    deps:
      - src/data/parse_nrel118_escalators_ts.py
      - data/raw/nrel118/additional-files-mti-118/Escalators.csv
      - src/utils/data_loaders/load_df_data.py
    params:
      - definitions.py:
          - GEN_TYPES
          - DATE_FORMAT
    outs:
      - data/parsed/nrel118_escalators_ts.csv

  parse_nrel118_hydros_nondisp_ts:
    desc: "Parse hydro plants time-series data from the NREL-118 dataset"
    cmd: python src/data/parse_nrel118_hydros_nondisp_ts.py
      data/raw/nrel118/additional-files-mti-118/Hydro_nondipatchable.csv
      data/parsed/nrel118_hydros_nondisp_ts.csv
    deps:
      - src/data/parse_nrel118_hydros_nondisp_ts.py
      - data/raw/nrel118/additional-files-mti-118/Hydro_nondipatchable.csv
      - src/utils/data_loaders/load_df_data.py
    params:
      - definitions.py:
          - DATE_FORMAT
    outs:
      - data/parsed/nrel118_hydros_nondisp_ts.csv

  parse_nrel118_hydros_ts:
    desc: "Parse time-series hydro plants data from the NREL-118 dataset"
    cmd: python src/data/parse_nrel118_hydros_ts.py
      "data/raw/nrel118/Input files/Hydro"
      data/parsed/nrel118_hydros_ts.csv
    deps:
      - src/data/parse_nrel118_hydros_ts.py
      - data/raw/nrel118/Input files/Hydro
      - src/utils/data_loaders/load_ts_data.py
    outs:
      - data/parsed/nrel118_hydros_ts.csv

  parse_nrel118_solars_ts:
    desc: "Parse time-series solar plants data from the NREL-118 dataset"
    cmd: python src/data/parse_nrel118_solars_ts.py
      "data/raw/nrel118/Input files/RT/Solar"
      data/parsed/nrel118_solars_ts.csv
    deps:
      - src/data/parse_nrel118_solars_ts.py
      - data/raw/nrel118/Input files/RT/Solar
      - src/utils/data_loaders/load_ts_data.py
    outs:
      - data/parsed/nrel118_solars_ts.csv

  parse_nrel118_winds_ts:
    desc: "Parse time-series wind plants data from the NREL-118 dataset"
    cmd: python src/data/parse_nrel118_winds_ts.py
      "data/raw/nrel118/Input files/RT/Wind"
      data/parsed/nrel118_winds_ts.csv
    deps:
      - src/data/parse_nrel118_winds_ts.py
      - data/raw/nrel118/Input files/RT/Wind
      - src/utils/data_loaders/load_ts_data.py
    outs:
      - data/parsed/nrel118_winds_ts.csv

  parse_nrel118_outages_ts:
    desc: "Parse time-series outage data from the NREL-118 dataset"
    cmd: python src/data/parse_nrel118_outages_ts.py
      "data/raw/nrel118/Input files/Others/GenOut.csv"
      data/parsed/nrel118_outages_ts.csv
    deps:
      - src/data/parse_nrel118_outages_ts.py
      - data/raw/nrel118/Input files/Others/GenOut.csv
      - src/utils/data_loaders/load_df_data.py
    params:
      - definitions.py:
          - GEN_TYPES
          - DATE_FORMAT
    outs:
      - data/parsed/nrel118_outages_ts.csv

  transform_loads:
    desc: "Combine necessary load variables for preparation stages"
    cmd: python src/data/transform_loads.py
      data/parsed/nrel118_buses.csv
      data/parsed/jeas118_loads.csv
      data/transformed/loads.csv
    deps:
      - data/parsed/nrel118_buses.csv
      - data/parsed/jeas118_loads.csv
      - src/data/transform_loads.py
      - src/utils/data_loaders/load_df_data.py
    outs:
      - data/transformed/loads.csv

  transform_gens_escalated_ts:
    desc: "Combine max output of generators and escalator values"
    cmd: python src/data/transform_gens_escalated_ts.py
      data/parsed/nrel118_gens.csv
      data/parsed/nrel118_escalators_ts.csv
      data/transformed/gens_escalated_ts.csv
    deps:
      - data/parsed/nrel118_gens.csv
      - data/parsed/nrel118_escalators_ts.csv
      - src/data/transform_gens_escalated_ts.py
      - src/utils/data_loaders/load_df_data.py
    outs:
      - data/transformed/gens_escalated_ts.csv

  prepare_buses:
    desc: "Build final bus dataset"
    cmd: python src/data/prepare_buses.py
      data/parsed/nrel118_buses.csv
      data/prepared/buses.csv
    deps:
      - data/parsed/nrel118_buses.csv
      - src/data/prepare_buses.py
      - src/utils/data_loaders/load_df_data.py
    outs:
      - data/prepared/buses.csv

  prepare_branches:
    desc: "Build final dataset with line and transformer info"
    cmd: python src/data/prepare_branches.py
      data/parsed/nrel118_lines.csv
      data/parsed/jeas118_lines.csv
      data/parsed/jeas118_trafos.csv
      data/prepared/buses.csv
      data/prepared/branches.csv
    deps:
      - src/data/prepare_branches.py
      - data/parsed/nrel118_lines.csv
      - data/parsed/jeas118_lines.csv
      - data/parsed/jeas118_trafos.csv
      - data/prepared/buses.csv
      - src/utils/data_loaders/load_df_data.py
    params:
      - definitions.py:
          - S_BASE__MVA
    outs:
      - data/prepared/branches.csv

  prepare_loads:
    desc: "Build final dataset with load info"
    cmd: python src/data/prepare_loads.py
      data/transformed/loads.csv
      data/prepared/loads.csv
    deps:
      - src/data/prepare_loads.py
      - data/transformed/loads.csv
      - src/utils/data_loaders/load_df_data.py
    outs:
      - data/prepared/loads.csv

  prepare_loads_ts:
    desc: "Build final dataset with load time-series data"
    cmd: python src/data/prepare_loads_ts.py
      data/transformed/loads.csv
      data/parsed/nrel118_loads_ts.csv
      data/prepared/loads_ts.csv
    deps:
      - src/data/prepare_loads_ts.py
      - data/transformed/loads.csv
      - data/parsed/nrel118_loads_ts.csv
      - src/utils/data_loaders/load_df_data.py
    outs:
      - data/prepared/loads_ts.csv

  prepare_gens:
    desc: "Build final dataset with generation info"
    cmd: python src/data/prepare_gens.py
      data/parsed/nrel118_gens.csv
      data/prepared/gens.csv
    deps:
      - src/data/prepare_gens.py
      - data/parsed/nrel118_gens.csv
      - src/utils/data_loaders/load_df_data.py
    outs:
      - data/prepared/gens.csv

  prepare_gens_ts:
    desc: "Build final dataset with generation time-series data"
    cmd: python src/data/prepare_gens_ts.py
      data/parsed/nrel118_winds_ts.csv
      data/parsed/nrel118_solars_ts.csv
      data/parsed/nrel118_hydros_ts.csv
      data/parsed/nrel118_hydros_nondisp_ts.csv
      data/transformed/gens_escalated_ts.csv
      data/parsed/nrel118_outages_ts.csv
      data/prepared/gens_ts.csv
    deps:
      - src/data/prepare_gens_ts.py
      - data/parsed/nrel118_winds_ts.csv
      - data/parsed/nrel118_solars_ts.csv
      - data/parsed/nrel118_hydros_ts.csv
      - data/parsed/nrel118_hydros_nondisp_ts.csv
      - data/transformed/gens_escalated_ts.csv
      - data/parsed/nrel118_outages_ts.csv
      - src/utils/data_loaders/load_df_data.py
    outs:
      - data/prepared/gens_ts.csv
