name: Publish dataset

on:
  release:
    types: [released, prereleased]

env:
  FOLDER_NAME: "dataset-${{ github.event.release.tag_name }}"

jobs:
  publish:
    name: Publish power flow cases and power system data
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry==1.2.2

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: poetry

      - name: Install packages
        run: poetry install

      - name: Run pipeline
        run: |
          export PYTHONPATH=$PWD
          poetry run python main.py

      - name: Collect data
        run: |
          mkdir ${{ env.FOLDER_NAME }}
          cp -r samples ${{ env.FOLDER_NAME }}/samples/
          cp -r data/prepared/ ${{ env.FOLDER_NAME }}/data/
          cp -r resources/plot ${{ env.FOLDER_NAME }}/plots/
          cp convention.md ${{ env.FOLDER_NAME }}/convention.md
          cp LICENSE ${{ env.FOLDER_NAME }}/LICENSE.txt
          cp resources/data_description.md ${{ env.FOLDER_NAME }}/README.md
          rm ./${{ env.FOLDER_NAME }}/**/.gitignore

      - name: Compress data
        run: |
          sudo apt-get install zip
          zip -r ${{ env.FOLDER_NAME }}.zip ${{ env.FOLDER_NAME }}/

      - name: Publish data
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "${{ env.FOLDER_NAME }}.zip"
          asset_name: "${{ env.FOLDER_NAME }}.zip"
          asset_content_type: application/zip
