name: Publish prepared power flow cases

on:
  release:
    types: [ released, prereleased ]

jobs:
  publish:
    name: Publish power flow cases
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry==1.2.2

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: poetry

      - name: Install packages
        run: poetry install

      - name: Run data preparation pipeline
        run: |
          export PYTHONPATH=$PWD
          poetry run python main.py

      - name: Add samples to zip archive
        run: |
          sudo apt-get install zip
          zip -r samples.zip samples/

      - name: Publish samples
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./samples.zip
          asset_name: samples.zip
          asset_content_type: application/zip
